name: 🎌 Daily Anime Quote

on:
  schedule:
    - cron: "0 0 * * *"          # Every day at 00:00 UTC
  workflow_dispatch:             # Manual trigger for testing

permissions:
  contents: write                # Needed to push the commit

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch anime quote & picture
        id: quote
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: |
          set -euo pipefail

          # ── 1. Random quote ----------------------------------------------------
          QUOTE_JSON=$(curl -fsSL --retry 3 --retry-delay 3 \
                       "https://yurippe.vercel.app/api/quotes?random=1")
          TEXT=$(echo "$QUOTE_JSON" | jq -r '.[0].quote')
          CHAR=$(echo "$QUOTE_JSON" | jq -r '.[0].character')
          ANIME=$(echo "$QUOTE_JSON" | jq -r '.[0].show')

          # ── 2. Google-Image via SerpAPI (GET query) ---------------------------
          SEARCH_Q="$(printf '%s' "${CHAR} ${ANIME}" | jq -sRr @uri)"
          IMG_JSON=$(curl -fsSL --retry 3 --retry-delay 3 \
            "https://serpapi.com/search.json?engine=google_images&q=${SEARCH_Q}&ijn=0&api_key=${SERPAPI_KEY}")

          IMG_URL=$(echo "$IMG_JSON" | jq -r '.images_results[0].original // empty')
          # Fallback placeholder if SerpAPI gives nothing
          [ -z "$IMG_URL" ] && \
            IMG_URL="https://64.media.tumblr.com/b7d8dc49e421a73b77efc6e31be68f7b/tumblr_mq5057LN0i1r9uvs7o1_500.gif"

          # ── 3. Escape strings for sed ----------------------------------------
          TEXT_ESC=$(echo "$TEXT"   | sed 's/[\/&]/\\&/g')
          CHAR_ESC=$(echo "$CHAR"   | sed 's/[\/&]/\\&/g')
          ANIME_ESC=$(echo "$ANIME" | sed 's/[\/&]/\\&/g')
          IMG_ESC=$(echo "$IMG_URL" | sed 's/[\/&]/\\&/g')

          # ── 4. Build new block -------------------------------------------------
          NEW_BLOCK="<div align=\"center\">\n  <blockquote style=\"font-style: italic;\">\n    <i>\"$TEXT_ESC\"</i>\n    <br>— $CHAR_ESC ($ANIME_ESC)\n  </blockquote>\n  <img src=\"$IMG_ESC\" width=\"400\"style=\"max-width:100%;height:auto;border-radius:8px;\">\n</div>"

          # ── 5. Update README.md ------------------------------------------------
          sed -i \
            -e '/<!-- ANIME_QUOTE_START -->/,/<!-- ANIME_QUOTE_END -->/c\<!-- ANIME_QUOTE_START -->\n'"$NEW_BLOCK"'\n<!-- ANIME_QUOTE_END -->' \
            README.md

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || \
            git commit -m "🎌 Auto-update anime quote"
          git push
